baseURL: 'http://localhost:1313'
languageCode: 'en-us'
title: "girl in thought, shamsa rageh"

# Theme-compatible menu structure
menu:
  main:
    - identifier: "opinion"
      name: "opinion"
      url: "/categories/opinion/"
      weight: 1
    - identifier: "art-culture"
      name: "art & culture"
      url: "/categories/art-culture/"
      weight: 2
    - identifier: "diary"
      name: "diary"
      url: "/categories/diary/"
      weight: 3
    - identifier: "about"
      name: "about"
      url: "/about/"
      weight: 4

params:
  theme: "auto"
  palette: "eink"
  showPostsSummary: true