baseURL: 'http://localhost:1313'
languageCode: 'en-us'
title: "girl in thought, shamsa rageh"
description: 'A minimal blog focused on ideas'

# Menu configuration
menu:
  main:
    # - name: 'archives'
    #   url: '/'
    #   weight: 1
    - name: 'opinion'
      url: '/categories/opinion/'
      weight: 1
    - name: 'art & culture'
      url: '/categories/art-culture/'
      weight: 2
    - name: 'reviews'
      url: '/categories/reviews/'
      weight: 3
    - name: 'diary'
      url: '/categories/diary/'
      weight: 4
    - name: 'about'
      url: '/about/'
      weight: 5
    - name: 'archives'
      url: '/'
      weight: 6  


# Pagination
pagination: 
  pagerSize: 10

# Markup settings
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
    lineNos: false

# Params for customisation
params:
  author: 'Shamsa Rageh'
  description: 'A minimal blog focused on ideas'